language: python
python:
  - "3.5"
  - "2.7"
install:
  - pip install coveralls
  - python setup.py -q install
script:
  -coverage run --source=rest_builder setup.py test
after_success:
  - coveralls
