"""empty message

Revision ID: 4e4de9b0361
Revises: None
Create Date: 2015-07-13 21:42:42.109005

"""

# revision identifiers, used by Alembic.
revision = '4e4de9b0361'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=31), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=31), nullable=True),
    sa.Column('password', sa.String(length=63), nullable=False),
    sa.Column('email', sa.String(length=63), nullable=True),
    sa.Column('database_uri', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship')
    op.drop_table('user')
    op.drop_table('resource')
    ### end Alembic commands ###
